import Spline, { SPEObject, SplineEvent } from "@splinetool/react-spline";
import { Application } from "@splinetool/runtime";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from "../components/navbar";
import Sidenav from "../components/sidenav";
import AboutMe from "../features/AboutMe";
import Projects from "../features/Projects";
import { Navigation } from "../interfaces/interfaces";

const listNavigation: Navigation[] = [
  { url: "/", text: "Home" },
  { url: "/#about-me", text: "About Me" },
  { url: "/#projects", text: "Projects" },
  { url: "/#contact", text: "Contact" },
];

const Home: NextPage = () => {
  const BlobRef = React.useRef(null);

  const onLoad = (spline: Application) => {
    const obj: SPEObject | undefined = spline.findObjectById(
      "0933f3b1-e19b-42dc-a05f-4b9dd8e9bead"
    );

    obj ? scaleUp(obj, 2.3) : null;
  };

  const scaleUp = (obj: SPEObject, num: number) => {
    obj.scale.x = num;
    obj.scale.y = num;
    obj.scale.z = num;
  };

  return (
    <div className=" bg-zinc-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidenav items={listNavigation} />
      <main>
        <Navbar items={listNavigation} />
        <div className="w-full h-screen relative flex content-center items-center">
          <h1 className="absolute text-white text-5xl left-8 md:left-1/3 right-8 md:right-1/3 md:text-center rounded-md backdrop-blur-lg backdrop-opacity-10 bg-white/10 md:bg-transparent p-10">
            Hello there! 👋
          </h1>
          <div className="bottom-20 md:left-1/4 md:right-1/4 absolute text-white rounded-md backdrop-blur-lg backdrop-opacity-10 bg-white/10 px-10 py-4 left-8 right-8">
            <p>
              I&apos;m an Informatics Engineering student from Indonesia,
              pursuing in frontend developer career.
            </p>
            <br />
            <div className="flex justify-center">
              <small className="text-zinc-400 mx-auto">
                scroll for more content
              </small>
            </div>
          </div>
          <Spline
            ref={BlobRef}
            onLoad={onLoad}
            scene="https://prod.spline.design/uyxLWFsBrBaflr2h/scene.splinecode"
          />
        </div>
        <AboutMe />
        <Projects />
      </main>
    </div>
  );
};

export default Home;
